export const data = {
    // The "HideIfSameAs" list is used to specify that a detailed binding such as "SelectTarget_Buggy"
    // need not be printed if the exact same button is bound to the more general version of that control
    // (in that case "SelectTarget").

    // Controls for the galaxy map
    "CamTranslateUp": {"Group": "Galaxy map", "Category": "UI", "Order": 1, "Name": "GalMap Up", "HideIfSameAs": []},
    "CamTranslateDown": {"Group": "Galaxy map", "Category": "UI", "Order": 2, "Name": "GalMap Down", "HideIfSameAs": []},
    "CamTranslateLeft": {"Group": "Galaxy map", "Category": "UI", "Order": 3, "Name": "GalMap Left", "HideIfSameAs": []},
    "CamTranslateRight": {"Group": "Galaxy map", "Category": "UI", "Order": 4, "Name": "GalMap Right", "HideIfSameAs": []},
    "CamTranslateForward": {"Group": "Galaxy map", "Category": "UI", "Order": 5, "Name": "GalMap Forward", "HideIfSameAs": []},
    "CamTranslateBackward": {"Group": "Galaxy map", "Category": "UI", "Order": 6, "Name": "GalMap Backward", "HideIfSameAs": []},
    "CamTranslateXAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 7, "Name": "GalMap X", "HideIfSameAs": []},
    "CamTranslateYAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 8, "Name": "GalMap Y", "HideIfSameAs": []},
    "CamTranslateZAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 9, "Name": "GalMap Z", "HideIfSameAs": []},
    "CamTranslateZHold": {"Group": "Galaxy map", "Category": "UI", "Order": 10, "Name": "GalMap Z Hold", "HideIfSameAs": []},
    "CamPitchAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 11, "Name": "GalMap Pitch", "HideIfSameAs": ["PitchAxisRaw"]},
    "CamPitchUp": {"Group": "Galaxy map", "Category": "UI", "Order": 12, "Name": "GalMap Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "CamPitchDown": {"Group": "Galaxy map", "Category": "UI", "Order": 13, "Name": "GalMap Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "CamYawAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 14, "Name": "GalMap Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "CamYawLeft": {"Group": "Galaxy map", "Category": "UI", "Order": 15, "Name": "GalMap Yaw Left", "HideIfSameAs": ["YawLeftButton"]},
    "CamYawRight": {"Group": "Galaxy map", "Category": "UI", "Order": 16, "Name": "GalMap Yaw Right", "HideIfSameAs": ["YawRightButton"]},
    "CamZoomAxis": {"Group": "Galaxy map", "Category": "UI", "Order": 17, "Name": "GalMap Zoom", "HideIfSameAs": []},
    "CamZoomIn": {"Group": "Galaxy map", "Category": "UI", "Order": 18, "Name": "GalMap Zoom In", "HideIfSameAs": []},
    "CamZoomOut": {"Group": "Galaxy map", "Category": "UI", "Order": 19, "Name": "GalMap Zoom Out", "HideIfSameAs": []},
    "GalaxyMapHome": {"Group": "Galaxy map", "Category": "UI", "Order": 20, "Name": "GalMap Home", "HideIfSameAs": []},

    // General items available on both ship and SRV
    "RadarRangeAxis": {"Group": "Misc", "Category": "Navigation", "Order": 1, "Name": "Sensor Range", "HideIfSameAs": []},
    "RadarDecreaseRange": {"Group": "Misc", "Category": "Navigation", "Order": 2, "Name": "Dec Sensor Range", "HideIfSameAs": []},
    "RadarIncreaseRange": {"Group": "Misc", "Category": "Navigation", "Order": 3, "Name": "Inc Sensor Range", "HideIfSameAs": []},
    "MicrophoneMute": {"Group": "Misc", "Category": "General", "Order": 4, "Name": "Microphone", "HideIfSameAs": []},
    "HMDReset": {"Group": "Misc", "Category": "General", "Order": 5, "Name": "Reset HMD", "HideIfSameAs": []},
    "OculusReset": {"Group": "Misc", "Category": "General", "Order": 6, "Name": "Reset Oculus", "HideIfSameAs": []},
    "Pause": {"Group": "Misc", "Category": "General", "Order": 8, "Name": "Main Menu", "HideIfSameAs": []},
    "FriendsMenu": {"Group": "Misc", "Category": "General", "Order": 9, "Name": "Friends", "HideIfSameAs": []},
    "CommanderCreator_Undo": {"Group": "Holo-Me", "Category": "General", "Order": 10, "Name": "Undo Holo-Me", "HideIfSameAs": []},
    "CommanderCreator_Redo": {"Group": "Holo-Me", "Category": "General", "Order": 11, "Name": "Redo Holo-Me", "HideIfSameAs": []},
    "CommanderCreator_Rotation_MouseToggle": {"Group": "Holo-Me", "Category": "General", "Order": 12, "Name": "Toggle Holo-Me Rotation", "HideIfSameAs": []},
    "CommanderCreator_Rotation": {"Group": "Holo-Me", "Category": "General", "Order": 13, "Name": "Rotate Holo-Me", "HideIfSameAs": []},
    "NightVisionToggle": {"Group": "Misc", "Category": "General", "Order": 14, "Name": "Night Vision", "HideIfSameAs": []},
    "OpenCodexGoToDiscovery": {"Group": "Misc", "Category": "General", "Order": 15, "Name": "Codex", "HideIfSameAs": []},
    "GalnetAudio_Play_Pause": {"Group": "Misc", "Category": "General", "Order": 16, "Name": "Play/Pause Audio", "HideIfSameAs": []},
    "GalnetAudio_SkipForward": {"Group": "Misc", "Category": "General", "Order": 17, "Name": "Next Audio Track", "HideIfSameAs": []},
    "GalnetAudio_SkipBackward": {"Group": "Misc", "Category": "General", "Order": 18, "Name": "Prev Audio Track", "HideIfSameAs": []},
    "GalnetAudio_ClearQueue": {"Group": "Misc", "Category": "General", "Order": 19, "Name": "Clear Audio Queue", "HideIfSameAs": []},

    // Head look 
    "HeadLookPitchAxis": {"Group": "Head look", "Category": "Navigation", "Order": 1, "Name": "Look Up/Down", "HideIfSameAs": []},
    "HeadLookPitchAxisRaw": {"Group": "Head look", "Category": "Navigation", "Order": 2, "Name": "Look Up/Down", "HideIfSameAs": []},
    "HeadLookPitchUp": {"Group": "Head look", "Category": "Navigation", "Order": 3, "Name": "Look Up", "HideIfSameAs": []},
    "HeadLookPitchDown": {"Group": "Head look", "Category": "Navigation", "Order": 4, "Name": "Look Down", "HideIfSameAs": []},
    "HeadLookYawAxis": {"Group": "Head look", "Category": "Navigation", "Order": 5, "Name": "Look Left/Right", "HideIfSameAs": []},
    "HeadLookYawAxisRaw": {"Group": "Head look", "Category": "Navigation", "Order": 6, "Name": "Look Left/Right", "HideIfSameAs": []},
    "HeadLookYawLeft": {"Group": "Head look", "Category": "Navigation", "Order": 7, "Name": "Look Left", "HideIfSameAs": []},
    "HeadLookYawRight": {"Group": "Head look", "Category": "Navigation", "Order": 8, "Name": "Look Right", "HideIfSameAs": []},
    "HeadLookReset": {"Group": "Head look", "Category": "Navigation", "Order": 9, "Name": "Reset Headlook", "HideIfSameAs": []},

    //
    // Controls only available in the SRV
    //
    // Driving
    "SteeringAxis": {"Group": "SRV", "Category": "Navigation", "Order": 1, "Name": "SRV Steer", "HideIfSameAs": []},
    "SteerLeftButton": {"Group": "SRV", "Category": "Navigation", "Order": 2, "Name": "Steer Left", "HideIfSameAs": ["YawLeftButton"]},
    "SteerRightButton": {"Group": "SRV", "Category": "Navigation", "Order": 3, "Name": "Steer Right", "HideIfSameAs": ["YawRightButton"]},
    "DriveSpeedAxis": {"Group": "SRV", "Category": "Navigation", "Order": 4, "Name": "Speed", "HideIfSameAs": ["ThrottleAxis"]},
    "IncreaseSpeedButtonPartial": {"Group": "SRV", "Category": "Navigation", "Order": 5, "Name": "Inc Speed", "HideIfSameAs": []},
    "DecreaseSpeedButtonPartial": {"Group": "SRV", "Category": "Navigation", "Order": 6, "Name": "Dec Speed", "HideIfSameAs": []},
    "IncreaseSpeedButtonMax": {"Group": "SRV", "Category": "Navigation", "Order": 7, "Name": "Maximum Speed", "HideIfSameAs": ["SetSpeed100"]},
    "DecreaseSpeedButtonMax": {"Group": "SRV", "Category": "Navigation", "Order": 8, "Name": "Zero Speed", "HideIfSameAs": ["SetSpeedZero"]},
    "BuggyPitchAxis": {"Group": "SRV", "Category": "Navigation", "Order": 9, "Name": "Pitch", "HideIfSameAs": ["PitchAxis", "PitchAxisRaw"]},
    "BuggyPitchUpButton": {"Group": "SRV", "Category": "Navigation", "Order": 11, "Name": "Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "BuggyPitchDownButton": {"Group": "SRV", "Category": "Navigation", "Order": 12, "Name": "Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "BuggyRollLeft": {"Group": "SRV", "Category": "Navigation", "Order": 13, "Name": "Roll Left", "HideIfSameAs": ["RollLeftButton"]},
    "BuggyRollAxisRaw": {"Group": "SRV", "Category": "Navigation", "Order": 14, "Name": "Roll", "HideIfSameAs": ["RollAxisRaw"]},
    "BuggyRollLeftButton": {"Group": "SRV", "Category": "Navigation", "Order": 15, "Name": "Roll Left", "HideIfSameAs": ["RollLeftButton"]},
    "BuggyRollRight": {"Group": "SRV", "Category": "Navigation", "Order": 16, "Name": "Roll Right", "HideIfSameAs": ["RollRightButton"]},
    "BuggyRollRightButton": {"Group": "SRV", "Category": "Navigation", "Order": 17, "Name": "Roll Right", "HideIfSameAs": ["RollRightButton"]},
    "AutoBreakBuggyButton": {"Group": "SRV", "Category": "Navigation", "Order": 18, "Name": "Handbrake", "HideIfSameAs": []},
    "BuggyToggleReverseThrottleInput": {"Group": "SRV", "Category": "Navigation", "Order": 19, "Name": "Reverse", "HideIfSameAs": ["ToggleReverseThrottleInput"]},
    "VerticalThrustersButton": {"Group": "SRV", "Category": "Navigation", "Order": 20, "Name": "Vertical Thrusters", "HideIfSameAs": []},
    "ToggleDriveAssist": {"Group": "SRV", "Category": "Navigation", "Order": 21, "Name": "Drive Assist", "HideIfSameAs": []},
    "HeadlightsBuggyButton": {"Group": "SRV", "Category": "Navigation", "Order": 22, "Name": "Lights", "HideIfSameAs": ["ShipSpotLightToggle"]},
    "ToggleCargoScoop_Buggy": {"Group": "SRV", "Category": "Navigation", "Order": 23, "Name": "Cargo Scoop", "HideIfSameAs": ["ToggleCargoScoop"]},
    "RecallDismissShip": {"Group": "SRV", "Category": "Navigation", "Order": 24, "Name": "Recall/Dismiss Ship", "HideIfSameAs": []},

     // Targeting and firing
    "SelectTarget_Buggy": {"Group": "SRV", "Category": "Combat", "Order": 101, "Name": "Target Ahead", "HideIfSameAs": ["SelectTarget"]},
    "ToggleBuggyTurretButton": {"Group": "SRV", "Category": "Combat", "Order": 102, "Name": "Turret Mode", "HideIfSameAs": []},
    "BuggyPrimaryFireButton": {"Group": "SRV", "Category": "Combat", "Order": 103, "Name": "Primary Weapons", "HideIfSameAs": ["PrimaryFire"]},
    "BuggySecondaryFireButton": {"Group": "SRV", "Category": "Combat", "Order": 104, "Name": "Secondary Weapons", "HideIfSameAs": ["SecondaryFire"]},
    "BuggyTurretPitchAxisRaw": {"Group": "SRV", "Category": "Combat", "Order": 106, "Name": "Turret Pitch", "HideIfSameAs": ["PitchAxisRaw"]},
    "BuggyTurretPitchDownButton": {"Group": "SRV", "Category": "Combat", "Order": 107, "Name": "Turret Down", "HideIfSameAs": ["PitchDownButton"]},
    "BuggyTurretPitchUpButton": {"Group": "SRV", "Category": "Combat", "Order": 108, "Name": "Turret Up", "HideIfSameAs": ["PitchUpButton"]},
    "BuggyTurretYawAxisRaw": {"Group": "SRV", "Category": "Combat", "Order": 110, "Name": "Turret Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "BuggyTurretYawLeftButton": {"Group": "SRV", "Category": "Combat", "Order": 111, "Name": "Turret Left", "HideIfSameAs": ["YawLeftButton"]},
    "BuggyTurretYawRightButton": {"Group": "SRV", "Category": "Combat", "Order": 112, "Name": "Turret Right", "HideIfSameAs": ["YawLeftButton"]},
    "BuggyCycleFireGroupNext": {"Group": "SRV", "Category": "Combat", "Order": 113, "Name": "Next Fire Group", "HideIfSameAs": ["CycleFireGroupNext"]},
    "BuggyCycleFireGroupPrevious": {"Group": "SRV", "Category": "Combat", "Order": 114, "Name": "Prev Fire Group", "HideIfSameAs": ["CycleFireGroupPrevious"]},

     // Managing power
    "ResetPowerDistribution_Buggy": {"Group": "SRV", "Category": "Combat", "Order": 201, "Name": "RST", "HideIfSameAs": ["ResetPowerDistribution"]},
    "IncreaseEnginesPower_Buggy": {"Group": "SRV", "Category": "Combat", "Order": 202, "Name": "ENG", "HideIfSameAs": ["IncreaseEnginesPower"]},
    "IncreaseSystemsPower_Buggy": {"Group": "SRV", "Category": "Combat", "Order": 203, "Name": "SYS", "HideIfSameAs": ["IncreaseSystemsPower"]},
    "IncreaseWeaponsPower_Buggy": {"Group": "SRV", "Category": "Combat", "Order": 204, "Name": "WEP", "HideIfSameAs": ["IncreaseWeaponsPower"]},

     // Navigation
    "GalaxyMapOpen_Buggy": {"Group": "SRV", "Category": "Navigation", "Order": 301, "Name": "GalMap", "HideIfSameAs": ["GalaxyMapOpen"]},
    "SystemMapOpen_Buggy": {"Group": "SRV", "Category": "Navigation", "Order": 302, "Name": "SysMap", "HideIfSameAs": ["SystemMapOpen"]},

     // UI
    "FocusCommsPanel_Buggy": {"Group": "SRV", "Order": 401, "Name": "Comms Panel", "HideIfSameAs": ["FocusCommsPanel"]},
    "FocusLeftPanel_Buggy": {"Group": "SRV", "Order": 402, "Name": "Nav Panel", "HideIfSameAs": ["FocusLeftPanel"]},
    "FocusRadarPanel_Buggy": {"Group": "SRV", "Order": 403, "Name": "Role Panel", "HideIfSameAs": ["FocusRadarPanel"]},
    "FocusRightPanel_Buggy": {"Group": "SRV", "Order": 404, "Name": "Systems Panel", "HideIfSameAs": ["FocusRightPanel"]},
    "QuickCommsPanel_Buggy": {"Group": "SRV", "Order": 405, "Name": "Quick Comms", "HideIfSameAs": ["QuickCommsPanel"]},
    "UIFocus_Buggy": {"Group": "SRV", "Order": 406, "Name": "UI Focus", "HideIfSameAs": ["UIFocus"]},

     // Misc
    "EjectAllCargo_Buggy": {"Group": "SRV", "Order": 501, "Name": "Eject All Cargo", "HideIfSameAs": ["EjectAllCargo"]},
    "HeadLookToggle_Buggy": {"Group": "SRV", "Order": 502, "Name": "Toggle Headlook", "HideIfSameAs": ["HeadLookToggle"]},

    //
    // Controls only available in the ship
    //
    // Flying
    "PitchAxisRaw": {"Group": "Ship", "Category": "Navigation", "Order": 2, "Name": "Pitch", "HideIfSameAs": []},
    "PitchUpButton": {"Group": "Ship", "Category": "Navigation", "Order": 3, "Name": "Pitch Up", "HideIfSameAs": []},
    "PitchDownButton": {"Group": "Ship", "Category": "Navigation", "Order": 4, "Name": "Pitch Down", "HideIfSameAs": []},
    "RollAxisRaw": {"Group": "Ship", "Category": "Navigation", "Order": 6, "Name": "Roll", "HideIfSameAs": []},
    "RollLeftButton": {"Group": "Ship", "Category": "Navigation", "Order": 7, "Name": "Roll Left", "HideIfSameAs": []},
    "RollRightButton": {"Group": "Ship", "Category": "Navigation", "Order": 8, "Name": "Roll Right", "HideIfSameAs": []},
    "YawAxisRaw": {"Group": "Ship", "Category": "Navigation", "Order": 10, "Name": "Yaw", "HideIfSameAs": []},
    "YawLeftButton": {"Group": "Ship", "Category": "Navigation", "Order": 11, "Name": "Yaw Left", "HideIfSameAs": []},
    "YawRightButton": {"Group": "Ship", "Category": "Navigation", "Order": 12, "Name": "Yaw Right", "HideIfSameAs": []},
    "YawToRollButton": {"Group": "Ship", "Category": "Navigation", "Order": 13, "Name": "Yaw To Roll", "HideIfSameAs": []},
    "ThrottleAxis": {"Group": "Ship", "Category": "Navigation", "Order": 14, "Name": "Throttle", "HideIfSameAs": []},
    "SetSpeed100": {"Group": "Ship", "Category": "Navigation", "Order": 16, "Name": "100% Throttle", "HideIfSameAs": []},
    "SetSpeed75": {"Group": "Ship", "Category": "Navigation", "Order": 17, "Name": "75% Throttle", "HideIfSameAs": []},
    "SetSpeed50": {"Group": "Ship", "Category": "Navigation", "Order": 18, "Name": "50% Throttle", "HideIfSameAs": []},
    "SetSpeed25": {"Group": "Ship", "Category": "Navigation", "Order": 19, "Name": "25% Throttle", "HideIfSameAs": []},
    "SetSpeedZero": {"Group": "Ship", "Category": "Navigation", "Order": 20, "Name": "All Stop", "HideIfSameAs": []},
    "SetSpeedMinus25": {"Group": "Ship", "Category": "Navigation", "Order": 21, "Name": "25% Reverse", "HideIfSameAs": []},
    "SetSpeedMinus50": {"Group": "Ship", "Category": "Navigation", "Order": 22, "Name": "50% Reverse", "HideIfSameAs": []},
    "SetSpeedMinus75": {"Group": "Ship", "Category": "Navigation", "Order": 23, "Name": "75% Reverse", "HideIfSameAs": []},
    "SetSpeedMinus100": {"Group": "Ship", "Category": "Navigation", "Order": 24, "Name": "100% Reverse", "HideIfSameAs": []},
    "AheadThrust": {"Group": "Ship", "Category": "Navigation", "Order": 25, "Name": "Forward Thrust", "HideIfSameAs": []},
    "ForwardKey": {"Group": "Ship", "Category": "Navigation", "Order": 26, "Name": "Forward Thrust", "HideIfSameAs": []},
    "ForwardThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 27, "Name": "Forward Thrust", "HideIfSameAs": []},
    "BackwardKey": {"Group": "Ship", "Category": "Navigation", "Order": 28, "Name": "Reverse Thrust", "HideIfSameAs": []},
    "BackwardThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 29, "Name": "Reverse thrust", "HideIfSameAs": []},
    "VerticalThrustRaw": {"Group": "Ship", "Category": "Navigation", "Order": 31, "Name": "Vertical Thrust", "HideIfSameAs": []},
    "UpThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 32, "Name": "Thrust Up", "HideIfSameAs": []},
    "DownThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 33, "Name": "Thrust Down", "HideIfSameAs": []},
    "LateralThrustRaw": {"Group": "Ship", "Category": "Navigation", "Order": 35, "Name": "Lateral Thrust", "HideIfSameAs": []},
    "LeftThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 36, "Name": "Thrust Left", "HideIfSameAs": []},
    "RightThrustButton": {"Group": "Ship", "Category": "Navigation", "Order": 37, "Name": "Thrust Right", "HideIfSameAs": []},
    "ToggleReverseThrottleInput": {"Group": "Ship", "Category": "Navigation", "Order": 38, "Name": "Reverse", "HideIfSameAs": []},
    "ToggleFlightAssist": {"Group": "Ship", "Category": "Navigation", "Order": 39, "Name": "Flight Assist", "HideIfSameAs": []},
    "UseBoostJuice": {"Group": "Ship", "Category": "Navigation", "Order": 40, "Name": "Boost", "HideIfSameAs": []},
    "ToggleButtonUpInput": {"Group": "Ship", "Category": "Navigation", "Order": 41, "Name": "Silent Running", "HideIfSameAs": []},
    "ToggleCargoScoop": {"Group": "Ship", "Category": "Navigation", "Order": 42, "Name": "Cargo Scoop", "HideIfSameAs": []},
    "ShipSpotLightToggle": {"Group": "Ship", "Category": "Navigation", "Order": 43, "Name": "Lights", "HideIfSameAs": []},
    "UseAlternateFlightValuesToggle": {"Group": "Ship", "Category": "Navigation", "Order": 44, "Name": "Alternate Controls", "HideIfSameAs": []},
    "PitchAxisAlternate": {"Group": "Ship", "Category": "Navigation", "Order": 45, "Name": "Pitch (Alt)", "HideIfSameAs": ["PitchAxisRaw"]},
    "RollAxisAlternate": {"Group": "Ship", "Category": "Navigation", "Order": 46, "Name": "Roll (Alt)", "HideIfSameAs": ["RollAxisRaw"]},
    "YawAxisAlternate": {"Group": "Ship", "Category": "Navigation", "Order": 47, "Name": "Yaw (Alt)", "HideIfSameAs": ["YawAxisRaw"]},
    "VerticalThrustAlternate": {"Group": "Ship", "Category": "Navigation", "Order": 48, "Name": "Vertical Thrust (Alt)", "HideIfSameAs": ["VerticalThrustRaw"]},
    "LateralThrustAlternate": {"Group": "Ship", "Category": "Navigation", "Order": 49, "Name": "Lateral Thrust (Alt)", "HideIfSameAs": ["LateralThrustRaw"]},

    // Selecting a target and firing
    "SelectTarget": {"Group": "Ship", "Category": "Combat", "Order": 101, "Name": "Target Ahead", "HideIfSameAs": []},
    "SelectHighestThreat": {"Group": "Ship", "Category": "Combat", "Order": 102, "Name": "Highest Threat", "HideIfSameAs": []},
    "CycleNextTarget": {"Group": "Ship", "Category": "Combat", "Order": 103, "Name": "Next Contact", "HideIfSameAs": []},
    "CyclePreviousTarget": {"Group": "Ship", "Category": "Combat", "Order": 104, "Name": "Prev Contact", "HideIfSameAs": []},
    "CycleNextHostileTarget": {"Group": "Ship", "Category": "Combat", "Order": 105, "Name": "Next Hostile", "HideIfSameAs": []},
    "CyclePreviousHostileTarget": {"Group": "Ship", "Category": "Combat", "Order": 106, "Name": "Prev Hostile", "HideIfSameAs": []},
    "DeployHardpointToggle": {"Group": "Ship", "Category": "Combat", "Order": 107, "Name": "Hardpoints", "HideIfSameAs": []},
    "PrimaryFire": {"Group": "Ship", "Category": "Combat", "Order": 108, "Name": "Fire 1", "HideIfSameAs": []},
    "SecondaryFire": {"Group": "Ship", "Category": "Combat", "Order": 109, "Name": "Fire 2", "HideIfSameAs": []},
    "CycleFireGroupNext": {"Group": "Ship", "Category": "Combat", "Order": 110, "Name": "Next Fire Group", "HideIfSameAs": []},
    "CycleFireGroupPrevious": {"Group": "Ship", "Category": "Combat", "Order": 111, "Name": "Prev Fire Group", "HideIfSameAs": []},
    "CycleNextSubsystem": {"Group": "Ship", "Category": "Combat", "Order": 112, "Name": "Next Subsystem", "HideIfSameAs": []},
    "CyclePreviousSubsystem": {"Group": "Ship", "Category": "Combat", "Order": 113, "Name": "Prev Subsystem", "HideIfSameAs": []},
    "FireChaffLauncher": {"Group": "Ship", "Category": "Combat", "Order": 114, "Name": "Chaff", "HideIfSameAs": []},
    "DeployHeatSink": {"Group": "Ship", "Category": "Combat", "Order": 116, "Name": "Heatsink", "HideIfSameAs": []},
    "UseShieldCell": {"Group": "Ship", "Category": "Combat", "Order": 117, "Name": "SCB", "HideIfSameAs": []},
    "ChargeECM": {"Group": "Ship", "Category": "Combat", "Order": 118, "Name": "ECM", "HideIfSameAs": []},

    // Managing power
    "ResetPowerDistribution": {"Group": "Ship", "Category": "Combat", "Order": 201, "Name": "RST", "HideIfSameAs": []},
    "IncreaseEnginesPower": {"Group": "Ship", "Category": "Combat", "Order": 202, "Name": "ENG", "HideIfSameAs": []},
    "IncreaseSystemsPower": {"Group": "Ship", "Category": "Combat", "Order": 203, "Name": "SYS", "HideIfSameAs": []},
    "IncreaseWeaponsPower": {"Group": "Ship", "Category": "Combat", "Order": 204, "Name": "WEP", "HideIfSameAs": []},

    // Fighter
    "OrderRequestDock": {"Group": "Fighter", "Category": "Combat", "Order": 251, "Name": "Dock SLF", "HideIfSameAs": []},
    "OrderDefensiveBehaviour": {"Group": "Fighter", "Category": "Combat", "Order": 252, "Name": "Be Defensive", "HideIfSameAs": []},
    "OrderAggressiveBehaviour": {"Group": "Fighter", "Category": "Combat", "Order": 253, "Name": "Be Aggressive", "HideIfSameAs": []},
    "OrderFocusTarget": {"Group": "Fighter", "Category": "Combat", "Order": 253, "Name": "Attack My Target", "HideIfSameAs": []},
    "OrderHoldFire": {"Group": "Fighter", "Category": "Combat", "Order": 254, "Name": "Hold Fire", "HideIfSameAs": []},
    "OrderHoldPosition": {"Group": "Fighter", "Category": "Combat", "Order": 256, "Name": "Hold Position", "HideIfSameAs": []},
    "OrderFollow": {"Group": "Fighter", "Category": "Combat", "Order": 257, "Name": "Follow", "HideIfSameAs": []},
    "OpenOrders": {"Group": "Fighter", "Category": "Combat", "Order": 258, "Name": "Crew Orders", "HideIfSameAs": []},

    // Multicrew
    "MultiCrewToggleMode": {"Group": "Multicrew", "Category": "General", "Order": 280, "Name": "Multicrew Mode", "HideIfSameAs": []},
    "MultiCrewThirdPersonPitchAxisRaw": {"Group": "Multicrew", "Category": "General", "Order": 281, "Name": "Pitch", "HideIfSameAs": ["PitchAxisRaw"]},
    "MultiCrewThirdPersonPitchUpButton": {"Group": "Multicrew", "Category": "General", "Order": 282, "Name": "Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "MultiCrewThirdPersonPitchDownButton": {"Group": "Multicrew", "Category": "General", "Order": 283, "Name": "Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "MultiCrewThirdPersonYawAxisRaw": {"Group": "Multicrew", "Category": "General", "Order": 284, "Name": "Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "MultiCrewThirdPersonYawLeftButton": {"Group": "Multicrew", "Category": "General", "Order": 285, "Name": "Yaw Left", "HideIfSameAs": ["YawLeftButton"]},
    "MultiCrewThirdPersonYawRightButton": {"Group": "Multicrew", "Category": "General", "Order": 286, "Name": "Yaw Right", "HideIfSameAs": ["YawRightButton"]},
    "MultiCrewThirdPersonFovAxisRaw": {"Group": "Multicrew", "Category": "General", "Order": 287, "Name": "Field of View", "HideIfSameAs": []},
    "MultiCrewThirdPersonFovOutButton": {"Group": "Multicrew", "Category": "General", "Order": 288, "Name": "Field of View Out", "HideIfSameAs": []},
    "MultiCrewThirdPersonFovInButton": {"Group": "Multicrew", "Category": "General", "Order": 289, "Name": "Field of View In", "HideIfSameAs": []},
    "MultiCrewPrimaryFire": {"Group": "Multicrew", "Category": "General", "Order": 290, "Name": "Fire 1", "HideIfSameAs": ["PrimaryFire"]},
    "MultiCrewSecondaryFire": {"Group": "Multicrew", "Category": "General", "Order": 292, "Name": "Fire 2", "HideIfSameAs": ["SecondaryFire"]},
    "MultiCrewPrimaryUtilityFire": {"Group": "Multicrew", "Category": "General", "Order": 292, "Name": "Primary Utility", "HideIfSameAs": []},
    "MultiCrewSecondaryUtilityFire": {"Group": "Multicrew", "Category": "General", "Order": 293, "Name": "Secondary Utility", "HideIfSameAs": []},
    "MultiCrewCockpitUICycleForward": {"Group": "Multicrew", "Category": "General", "Order": 294, "Name": "UI Forward", "HideIfSameAs": ["UI_Right"]},
    "MultiCrewCockpitUICycleBackward": {"Group": "Multicrew", "Category": "General", "Order": 295, "Name": "UI Backward", "HideIfSameAs": ["UI_Left"]},

    // Navigation
    "GalaxyMapOpen": {"Group": "Ship", "Category": "Navigation", "Order": 301, "Name": "Galaxy Map", "HideIfSameAs": []},
    "SystemMapOpen": {"Group": "Ship", "Category": "Navigation", "Order": 302, "Name": "System Map", "HideIfSameAs": []},
    "HyperSuperCombination": {"Group": "Ship", "Category": "Navigation", "Order": 303, "Name": "Hyperspace/Supercruise", "HideIfSameAs": []},
    "Hyperspace": {"Group": "Ship", "Category": "Navigation", "Order": 304, "Name": "Hyperspace", "HideIfSameAs": []},
    "EngageSupercruise": {"Group": "Ship", "Category": "Navigation", "Order": 305, "Name": "Supercruise", "HideIfSameAs": []},
    "Supercruise": {"Group": "Ship", "Category": "Navigation", "Order": 306, "Name": "Supercruise", "HideIfSameAs": []},
    "TargetNextRouteSystem": {"Group": "Ship", "Category": "Navigation", "Order": 307, "Name": "Next Jump Dest", "HideIfSameAs": []},

    // Wings
    "TargetWingman0": {"Group": "Ship", "Order": 401, "Name": "Wingman 1", "HideIfSameAs": []},
    "TargetWingman1": {"Group": "Ship", "Order": 402, "Name": "Wingman 2", "HideIfSameAs": []},
    "TargetWingman2": {"Group": "Ship", "Order": 403, "Name": "Wingman 3", "HideIfSameAs": []},
    "SelectTargetsTarget": {"Group": "Ship", "Order": 404, "Name": "Wingman\"s target", "HideIfSameAs": []},
    "WingNavLock": {"Group": "Ship", "Order": 405, "Name": "Wingman Navlock", "HideIfSameAs": []},

    // UI
    "UIFocus": {"Group": "Ship", "Order": 501, "Name": "UI Focus", "HideIfSameAs": []},
    "FocusCommsPanel": {"Group": "Ship", "Order": 502, "Name": "Comms Panel", "HideIfSameAs": []},
    "QuickCommsPanel": {"Group": "Ship", "Order": 503, "Name": "Quick Comms", "HideIfSameAs": []},
    "FocusLeftPanel": {"Group": "Ship", "Order": 504, "Name": "Nav Panel", "HideIfSameAs": []},
    "FocusRightPanel": {"Group": "Ship", "Order": 505, "Name": "Systems Panel", "HideIfSameAs": []},
    "FocusRadarPanel": {"Group": "Ship", "Order": 506, "Name": "Role Panel", "HideIfSameAs": []},
    "PlayerHUDModeToggle": {"Group": "Ship", "Category": "General", "Order": 507, "Name": "HUD Mode", "HideIfSameAs": []},

    // Landing
    "LandingGearToggle": {"Group": "Ship", "Category": "Navigation", "Order": 601, "Name": "Landing Gear", "HideIfSameAs": []},
    "PitchAxis_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 602, "Name": "Pitch (Lndg)", "HideIfSameAs": ["PitchAxisRaw"]},
    "PitchUpButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 603, "Name": "Pitch Up (Lndg)", "HideIfSameAs": ["PitchUpButton"]},
    "PitchDownButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 604, "Name": "Pitch Down (Lndg)", "HideIfSameAs": ["PitchDownButton"]},
    "RollAxis_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 605, "Name": "Roll (Lndg)", "HideIfSameAs": ["RollAxisRaw"]},
    "RollLeftButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 606, "Name": "Roll Left (Lndg)", "HideIfSameAs": ["RollLeftButton"]},
    "RollRightButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 607, "Name": "Roll Right (Lndg)", "HideIfSameAs": ["RollRightButton"]},
    "YawAxis_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 608, "Name": "Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "YawLeftButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 609, "Name": "Yaw Left (Lndg)", "HideIfSameAs": ["YawLeftButton"]},
    "YawRightButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 610, "Name": "Yaw Right (Lndg)", "HideIfSameAs": ["YawRightButton"]},
    "AheadThrust_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 611, "Name": "Forward Thrust (Lndg)", "HideIfSameAs": ["AheadThrust"]},
    "ForwardThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 612, "Name": "Forward Thrust (Lndg)", "HideIfSameAs": ["ForwardThrustButton"]},
    "BackwardThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 613, "Name": "Reverse Thrust (Lndg)", "HideIfSameAs": ["BackwardThrustButton"]},
    "VerticalThrust_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 614, "Name": "Vertical Thrust (Lndg)", "HideIfSameAs": ["VerticalThrustRaw"]},
    "UpThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 615, "Name": "Thrust Up (Lndg)", "HideIfSameAs": ["UpThrustButton"]},
    "DownThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 616, "Name": "Thrust Down (Lndg)", "HideIfSameAs": ["DownThrustButton"]},
    "LateralThrust_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 617, "Name": "Lateral Thrust (Lndg)", "HideIfSameAs": ["LateralThrustRaw"]},
    "LeftThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 618, "Name": "Thrust Left (Lndg)", "HideIfSameAs": ["LeftThrustButton"]},
    "RightThrustButton_Landing": {"Group": "Ship", "Category": "Navigation", "Order": 619, "Name": "Thrust Right (Lndg)", "HideIfSameAs": ["RightThrustButton"]},
    "DisableRotationCorrectToggle": {"Group": "Ship", "Category": "Navigation", "Order": 620, "Name": "Rotational Correction", "HideIfSameAs": []},

    // Scanners
    "ExplorationFSSEnter": {"Group": "Scanners", "Category": "General", "Order": 1, "Name": "Enter FSS", "HideIfSameAs": []},
    "ExplorationFSSCameraPitch": {"Group": "Scanners", "Category": "General", "Order": 2, "Name": "FSS Pitch ", "HasAnalogue": false, "HideIfSameAs": ["PitchAxisRaw"]},
    "ExplorationFSSCameraPitchIncreaseButton": {"Group": "Scanners", "Category": "General", "Order": 3, "Name": "FSS Pitch Up ", "HideIfSameAs": ["PitchUpButton"]},
    "ExplorationFSSCameraPitchDecreaseButton": {"Group": "Scanners", "Category": "General", "Order": 4, "Name": "FSS Pitch Down ", "HideIfSameAs": ["PitchDownButton"]},
    "ExplorationFSSCameraYaw": {"Group": "Scanners", "Category": "General", "Order": 5, "Name": "FSS Yaw ", "HasAnalogue": false, "HideIfSameAs": ["YawAxisRaw"]},
    "ExplorationFSSCameraYawIncreaseButton": {"Group": "Scanners", "Category": "General", "Order": 6, "Name": "FSS Yaw Right ", "HideIfSameAs": ["YawRightButton"]},
    "ExplorationFSSCameraYawDecreaseButton": {"Group": "Scanners", "Category": "General", "Order": 7, "Name": "FSS Yaw Left ", "HideIfSameAs": ["YawLeftButton"]},
    "ExplorationFSSZoomIn": {"Group": "Scanners", "Category": "General", "Order": 8, "Name": "Zoom FSS In", "HideIfSameAs": []},
    "ExplorationFSSZoomOut": {"Group": "Scanners", "Category": "General", "Order": 9, "Name": "Zoom FSS Out", "HideIfSameAs": []},
    "ExplorationFSSMiniZoomIn": {"Group": "Scanners", "Category": "General", "Order": 10, "Name": "Step Zoom FSS In", "HideIfSameAs": []},
    "ExplorationFSSMiniZoomOut": {"Group": "Scanners", "Category": "General", "Order": 11, "Name": "Step Zoom FSS Out", "HideIfSameAs": []},
    "ExplorationFSSRadioTuningX_Raw": {"Group": "Scanners", "Category": "General", "Order": 12, "Name": "FSS Tuning", "HasAnalogue": false, "HideIfSameAs": []},
    "ExplorationFSSRadioTuningX_Increase": {"Group": "Scanners", "Category": "General", "Order": 13, "Name": "FSS Tune Right", "HideIfSameAs": []},
    "ExplorationFSSRadioTuningX_Decrease": {"Group": "Scanners", "Category": "General", "Order": 14, "Name": "FSS Tune Left", "HideIfSameAs": []},
    "ExplorationFSSRadioTuningAbsoluteX": {"Group": "Scanners", "Category": "General", "Order": 15, "Name": "FSS Tuning", "HasAnalogue": false, "HideIfSameAs": []},
    "ExplorationFSSDiscoveryScan": {"Group": "Scanners", "Category": "General", "Order": 16, "Name": "FSS Honk", "HideIfSameAs": []},
    "ExplorationFSSQuit": {"Group": "Scanners", "Category": "General", "Order": 17, "Name": "Exit FSS", "HideIfSameAs": []},
    "ExplorationFSSTarget": {"Group": "Scanners", "Category": "General", "Order": 18, "Name": "Target FSS", "HideIfSameAs": []},
    "ExplorationFSSShowHelp": {"Group": "Scanners", "Category": "General", "Order": 19, "Name": "FSS Help", "HideIfSameAs": []},
    "ExplorationSAAChangeScannedAreaViewToggle": {"Group": "Scanners", "Category": "General", "Order": 20, "Name": "Toggle Planet Front/Back", "HideIfSameAs": []},
    "ExplorationSAAExitThirdPerson": {"Group": "Scanners", "Category": "General", "Order": 21, "Name": "Exit DSS", "HideIfSameAs": []},
    "SAAThirdPersonPitchAxisRaw": {"Group": "Scanners", "Category": "General", "Order": 281, "Name": "Pitch (DSS)", "HideIfSameAs": ["PitchAxisRaw"]},
    "SAAThirdPersonPitchUpButton": {"Group": "Scanners", "Category": "General", "Order": 282, "Name": "Pitch Up (DSS)", "HideIfSameAs": ["PitchUpButton"]},
    "SAAThirdPersonPitchDownButton": {"Group": "Scanners", "Category": "General", "Order": 283, "Name": "Pitch Down (DSS)", "HideIfSameAs": ["PitchDownButton"]},
    "SAAThirdPersonYawAxisRaw": {"Group": "Scanners", "Category": "General", "Order": 284, "Name": "DSS Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "SAAThirdPersonYawLeftButton": {"Group": "Scanners", "Category": "General", "Order": 285, "Name": "Yaw Left (DSS)", "HideIfSameAs": ["YawLeftButton"]},
    "SAAThirdPersonYawRightButton": {"Group": "Scanners", "Category": "General", "Order": 286, "Name": "Yaw Right (DSS)", "HideIfSameAs": ["YawRightButton"]},
    "SAAThirdPersonFovAxisRaw": {"Group": "Scanners", "Category": "General", "Order": 287, "Name": "DSS Field of View", "HideIfSameAs": []},
    "SAAThirdPersonFovOutButton": {"Group": "Scanners", "Category": "General", "Order": 288, "Name": "DSS Field of View Out", "HideIfSameAs": []},
    "SAAThirdPersonFovInButton": {"Group": "Scanners", "Category": "General", "Order": 289, "Name": "DSS Field of View In", "HideIfSameAs": []},

    // Misc
    "EjectAllCargo": {"Group": "Ship", "Category": "General", "Order": 701, "Name": "Eject All Cargo", "HideIfSameAs": []},
    "HeadLookToggle": {"Group": "Ship", "Category": "General", "Order": 702, "Name": "Toggle Headlook", "HideIfSameAs": []},
    "OrbitLinesToggle": {"Group": "Ship", "Category": "General", "Order": 703, "Name": "Orbit Lines", "HideIfSameAs": []},
    "ShowPGScoreSummaryInput": {"Group": "Ship", "Category": "General", "Order": 704, "Name": "CQC Score", "HideIfSameAs": []},
    "MouseReset": {"Group": "Ship", "Category": "General", "Order": 705, "Name": "Reset Mouse", "HideIfSameAs": []},
    "WeaponColourToggle": {"Group": "Ship", "Category": "General", "Order": 706, "Name": "Weapon Colour", "HideIfSameAs": []},
    "EngineColourToggle": {"Group": "Ship", "Category": "General", "Order": 707, "Name": "Engine Colour", "HideIfSameAs": []},

    // Camera
    "PhotoCameraToggle": {"Group": "Camera", "Category": "Camera", "Order": 801, "Name": "External Cam", "HideIfSameAs": []},
    "PhotoCameraToggle_Buggy": {"Group": "Camera", "Category": "Camera", "Order": 802, "Name": "External Cam", "HideIfSameAs": ["PhotoCameraToggle"]},
    "ToggleFreeCam": {"Group": "Camera", "Category": "General", "Order": 803, "Name": "Free Cam", "HideIfSameAs": []},
    "QuitCamera": {"Group": "Camera", "Category": "General", "Order": 804, "Name": "Exit free Cam", "HideIfSameAs": ["ToggleFreeCam"]},
    "VanityCameraOne": {"Group": "Camera", "Category": "General", "Order": 805, "Name": "Cam - Cockpit Front", "HideIfSameAs": []},
    "VanityCameraTwo": {"Group": "Camera", "Category": "General", "Order": 806, "Name": "Cam - Cockpit Back", "HideIfSameAs": []},
    "VanityCameraThree": {"Group": "Camera", "Category": "General", "Order": 808, "Name": "Cam - Commander 1", "HideIfSameAs": []},
    "VanityCameraFour": {"Group": "Camera", "Category": "General", "Order": 808, "Name": "Cam - Commander 2", "HideIfSameAs": []},
    "VanityCameraFive": {"Group": "Camera", "Category": "General", "Order": 809, "Name": "Cam - Co-Pilot 1", "HideIfSameAs": []},
    "VanityCameraSix": {"Group": "Camera", "Category": "General", "Order": 810, "Name": "Cam - Co-Pilot 2", "HideIfSameAs": []},
    "VanityCameraSeven": {"Group": "Camera", "Category": "General", "Order": 811, "Name": "Cam - Front", "HideIfSameAs": []},
    "VanityCameraEight": {"Group": "Camera", "Category": "General", "Order": 812, "Name": "Cam - Back", "HideIfSameAs": []},
    "VanityCameraNine": {"Group": "Camera", "Category": "General", "Order": 813, "Name": "Cam - Low", "HideIfSameAs": []},
    "VanityCameraScrollRight": {"Group": "Camera", "Category": "General", "Order": 814, "Name": "Next Cam", "HideIfSameAs": []},
    "VanityCameraScrollLeft": {"Group": "Camera", "Category": "General", "Order": 815, "Name": "Prev Cam", "HideIfSameAs": []},
    "FreeCamToggleHUD": {"Group": "Camera", "Category": "General", "Order": 816, "Name": "Toggle HUD", "HideIfSameAs": []},
    "FreeCamSpeedInc": {"Group": "Camera", "Category": "General", "Order": 817, "Name": "Inc Cam Speed", "HideIfSameAs": []},
    "FreeCamSpeedDec": {"Group": "Camera", "Category": "General", "Order": 818, "Name": "Dec Cam Speed", "HideIfSameAs": []},
    "FreeCamZoomIn": {"Group": "Camera", "Category": "General", "Order": 819, "Name": "Zoom In", "HideIfSameAs": []},
    "FreeCamZoomOut": {"Group": "Camera", "Category": "General", "Order": 820, "Name": "Zoom Out", "HideIfSameAs": []},
    "MoveFreeCamX": {"Group": "Camera", "Category": "General", "Order": 821, "Name": "Cam X", "HideIfSameAs": []},
    "MoveFreeCamLeft": {"Group": "Camera", "Category": "General", "Order": 822, "Name": "Cam Left", "HideIfSameAs": []},
    "MoveFreeCamRight": {"Group": "Camera", "Category": "General", "Order": 823, "Name": "Cam Right", "HideIfSameAs": []},
    "MoveFreeCamY": {"Group": "Camera", "Category": "General", "Order": 824, "Name": "Cam Y", "HideIfSameAs": []},
    "MoveFreeCamUp": {"Group": "Camera", "Category": "General", "Order": 825, "Name": "Cam Up", "HideIfSameAs": []},
    "MoveFreeCamDown": {"Group": "Camera", "Category": "General", "Order": 826, "Name": "Cam Down", "HideIfSameAs": []},
    "MoveFreeCamZ": {"Group": "Camera", "Category": "General", "Order": 827, "Name": "Cam Z", "HideIfSameAs": []},
    "MoveFreeCamForward": {"Group": "Camera", "Category": "General", "Order": 828, "Name": "Cam Forwards", "HideIfSameAs": []},
    "MoveFreeCamBackwards": {"Group": "Camera", "Category": "General", "Order": 829, "Name": "Cam Backwards", "HideIfSameAs": []},
    "PitchCamera": {"Group": "Camera", "Category": "General", "Order": 830, "Name": "Cam Pitch", "HideIfSameAs": ["PitchAxisRaw"]},
    "PitchCameraUp": {"Group": "Camera", "Category": "General", "Order": 831, "Name": "Cam Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "PitchCameraDown": {"Group": "Camera", "Category": "General", "Order": 832, "Name": "Cam Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "RollCamera": {"Group": "Camera", "Category": "General", "Order": 833, "Name": "Cam Roll", "HideIfSameAs": ["RollAxisRaw"]},
    "RollCameraLeft": {"Group": "Camera", "Category": "General", "Order": 834, "Name": "Cam Roll Left", "HideIfSameAs": ["RollLeftButton"]},
    "RollCameraRight": {"Group": "Camera", "Category": "General", "Order": 835, "Name": "Cam Roll Right", "HideIfSameAs": ["RollRightButton"]},
    "YawCamera": {"Group": "Camera", "Category": "General", "Order": 836, "Name": "Cam Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "YawCameraLeft": {"Group": "Camera", "Category": "General", "Order": 837, "Name": "Cam Yaw Left", "HideIfSameAs": ["YawLeftButton"]},
    "YawCameraRight": {"Group": "Camera", "Category": "General", "Order": 838, "Name": "Cam Yaw Right", "HideIfSameAs": ["YawRightButton"]},
    "ToggleRotationLock": {"Group": "Camera", "Category": "General", "Order": 839, "Name": "Cam Rotation Lock", "HideIfSameAs": []},
    "ToggleReverseThrottleInputFreeCam": {"Group": "Camera", "Category": "General", "Order": 840, "Name": "Cam Reverse", "HideIfSameAs": ["ToggleReverseThrottleInput", "BuggyToggleReverseThrottleInput"]},
    "FixCameraRelativeToggle": {"Group": "Camera", "Category": "General", "Order": 841, "Name": "Lock to Vehicle", "HideIfSameAs": []},
    "FixCameraWorldToggle": {"Group": "Camera", "Category": "General", "Order": 842, "Name": "Lock to World", "HideIfSameAs": []},
    "ToggleAdvanceMode": {"Group": "Camera", "Category": "General", "Order": 843, "Name": "Advanced Cam", "HideIfSameAs": []},
    "FStopInc": {"Group": "Camera", "Category": "General", "Order": 844, "Name": "Inc Blur", "HideIfSameAs": []},
    "FStopDec": {"Group": "Camera", "Category": "General", "Order": 845, "Name": "Dec Blur", "HideIfSameAs": []},
    "FocusDistanceInc": {"Group": "Camera", "Category": "General", "Order": 846, "Name": "Focus Further", "HideIfSameAs": []},
    "FocusDistanceDec": {"Group": "Camera", "Category": "General", "Order": 847, "Name": "Focus Nearer", "HideIfSameAs": []},

    // Store camera
    "StoreEnableRotation": {"Group": "Camera", "Category": "Camera", "Order": 901, "Name": "Store Cam Rotation", "HideIfSameAs": []},
    "StorePitchCamera": {"Group": "Camera", "Category": "Camera", "Order": 902, "Name": "Store Cam Pitch", "HideIfSameAs": ["PitchAxisRaw"]},
    "StorePitchCameraUp": {"Group": "Camera", "Category": "Camera", "Order": 903, "Name": "Store Cam Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "StorePitchCameraDown": {"Group": "Camera", "Category": "Camera", "Order": 904, "Name": "Store Cam Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "StoreYawCamera": {"Group": "Camera", "Category": "Camera", "Order": 905, "Name": "Store Cam Yaw", "HideIfSameAs": ["YawAxisRaw"]},
    "StoreYawCameraLeft": {"Group": "Camera", "Category": "Camera", "Order": 906, "Name": "Store Cam Yaw Left", "HideIfSameAs": ["YawLeftButton"]},
    "StoreYawCameraRight": {"Group": "Camera", "Category": "Camera", "Order": 907, "Name": "Store Cam Yaw Right", "HideIfSameAs": ["YawRightButton"]},
    "StoreCamZoomIn": {"Group": "Camera", "Category": "Camera", "Order": 908, "Name": "Store Cam Zoom In", "HideIfSameAs": []},
    "StoreCamZoomOut": {"Group": "Camera", "Category": "Camera", "Order": 909, "Name": "Store Cam Zoom Out", "HideIfSameAs": []},
    "StoreToggle": {"Group": "Camera", "Category": "Camera", "Order": 910, "Name": "Store Toggle Preview", "HideIfSameAs": []},

    //
    // Controls for the UI panels
    //
    "UI_Up": {"Group": "UI", "Category": "UI", "Order": 1, "Name": "UI Up", "HideIfSameAs": []},
    "UI_Down": {"Group": "UI", "Category": "UI", "Order": 2, "Name": "UI Down", "HideIfSameAs": []},
    "UI_Left": {"Group": "UI", "Category": "UI", "Order": 3, "Name": "UI Left", "HideIfSameAs": []},
    "UI_Right": {"Group": "UI", "Category": "UI", "Order": 4, "Name": "UI Right", "HideIfSameAs": []},
    "CycleNextPanel": {"Group": "UI", "Category": "UI", "Order": 5, "Name": "Next Panel", "HideIfSameAs": []},
    "CyclePreviousPanel": {"Group": "UI", "Category": "UI", "Order": 6, "Name": "Prev Panel", "HideIfSameAs": []},
    "UI_Select": {"Group": "UI", "Category": "UI", "Order": 7, "Name": "UI Select", "HideIfSameAs": []},
    "UI_Back": {"Group": "UI", "Category": "UI", "Order": 8, "Name": "UI Back", "HideIfSameAs": []},
    "UI_Toggle": {"Group": "UI", "Category": "UI", "Order": 9, "Name": "UI Toggle", "HideIfSameAs": []},
    "CycleNextPage": {"Group": "UI", "Category": "UI", "Order": 10, "Name": "Next Page", "HideIfSameAs": []},
    "CyclePreviousPage": {"Group": "UI", "Category": "UI", "Order": 11, "Name": "Prev Page", "HideIfSameAs": []},

    //
    // Controls only available On Foot
    //

    // Motion
    "HumanoidForwardAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 4, "Name": "Fwd/Back", "HideIfSameAs": ["ThrottleAxis"]},
    "HumanoidForwardButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 5, "Name": "Fwd", "HideIfSameAs": ["ForwardKey"]},
    "HumanoidBackwardButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 6, "Name": "Back", "HideIfSameAs": ["BackwardKey"]},
    "HumanoidPitchAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 9, "Name": "Pitch", "HideIfSameAs": ["PitchAxis", "PitchAxisRaw"]},
    "HumanoidPitchUpButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 11, "Name": "Pitch Up", "HideIfSameAs": ["PitchUpButton"]},
    "HumanoidPitchDownButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 12, "Name": "Pitch Down", "HideIfSameAs": ["PitchDownButton"]},
    "HumanoidStrafeAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 13, "Name": "Strafe", "HideIfSameAs": ["RollAxisRaw"]},
    "HumanoidStrafeLeftButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 14, "Name": "Strafe Left", "HideIfSameAs": ["RollLeftButton"]},
    "HumanoidStrafeRightButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 15, "Name": "Strafe Right", "HideIfSameAs": ["RollRightButton"]},
    "HumanoidRotateAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 16, "Name": "Turn", "HideIfSameAs": ["YawAxisRaw"]},
    "HumanoidRotateLeftButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 17, "Name": "Turn Left", "HideIfSameAs": ["YawLeftButton"]},
    "HumanoidRotateRightButton": {"Group": "OnFoot", "Category": "Navigation", "Order": 18, "Name": "Turn Right", "HideIfSameAs": ["YawRightButton"]},

    // Targeting and firing
    "HumanoidPrimaryFireButton": {"Group": "OnFoot", "Category": "Combat", "Order": 100, "Name": "Fire", "HideIfSameAs": ["PrimaryFire"]},
    "HumanoidActivateSuitAbilityButton": {"Group": "OnFoot", "Category": "Combat", "Order": 101, "Name": "Suit Tool", "HideIfSameAs": []},
    "HumanoidConflictContextualUI": {"Group": "OnFoot", "Category": "Combat", "Order": 102, "Name": "Combat UI", "HideIfSameAs": []},
    "HumanoidConflictContextualUIButton": {"Group": "OnFoot", "Category": "Combat", "Order": 103, "Name": "Combat UI", "HideIfSameAs": []},
    "HumanoidCrouchButton": {"Group": "OnFoot", "Category": "Combat", "Order": 104, "Name": "Crouch", "HideIfSameAs": []},
    "HumanoidHideWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 105, "Name": "Holster", "HideIfSameAs": []},
    "HumanoidJumpButton": {"Group": "OnFoot", "Category": "Combat", "Order": 106, "Name": "Jump", "HideIfSameAs": []},
    "HumanoidMeleeButton": {"Group": "OnFoot", "Category": "Combat", "Order": 107, "Name": "Melee", "HideIfSameAs": []},
    "HumanoidOpenAccessPanelButton": {"Group": "OnFoot", "Category": "Combat", "Order": 108, "Name": "Open Access Panel", "HideIfSameAs": []},
    "HumanoidPrimaryInteractButton": {"Group": "OnFoot", "Category": "Combat", "Order": 109, "Name": "Interact", "HideIfSameAs": []},
    "HumanoidPulseScanButton": {"Group": "OnFoot", "Category": "Combat", "Order": 110, "Name": "Pulse Scan", "HideIfSameAs": []},
    "HumanoidReloadButton": {"Group": "OnFoot", "Category": "Combat", "Order": 111, "Name": "Reload", "HideIfSameAs": []},
    "HumanoidSecondaryInteractButton": {"Group": "OnFoot", "Category": "Combat", "Order": 112, "Name": "Interact 2", "HideIfSameAs": []},
    "HumanoidSelectNextGrenadeTypeButton": {"Group": "OnFoot", "Category": "Combat", "Order": 113, "Name": "Next Grenade", "HideIfSameAs": []},
    "HumanoidSelectNextWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 114, "Name": "Next WEP", "HideIfSameAs": []},
    "HumanoidSelectPreviousGrenadeTypeButton": {"Group": "OnFoot", "Category": "Combat", "Order": 115, "Name": "Prev Grenade", "HideIfSameAs": []},
    "HumanoidSelectPreviousWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 116, "Name": "Prev WEP", "HideIfSameAs": []},
    "HumanoidSelectPrimaryWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 117, "Name": "WEP 1", "HideIfSameAs": []},
    "HumanoidSelectSecondaryWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 118, "Name": "WEP 2", "HideIfSameAs": []},
    "HumanoidSelectUtilityWeaponButton": {"Group": "OnFoot", "Category": "Combat", "Order": 119, "Name": "Select Util", "HideIfSameAs": []},
    "HumanoidSprintButton": {"Group": "OnFoot", "Category": "Combat", "Order": 120, "Name": "Sprint", "HideIfSameAs": []},
    "HumanoidSwitchToCompAnalyser": {"Group": "OnFoot", "Category": "Combat", "Order": 121, "Name": "Comp Analyser", "HideIfSameAs": []},
    "HumanoidSwitchToRechargeTool": {"Group": "OnFoot", "Category": "Combat", "Order": 122, "Name": "Recharge Tool", "HideIfSameAs": []},
    "HumanoidSwitchToSuitTool": {"Group": "OnFoot", "Category": "Combat", "Order": 123, "Name": "Suit Tool", "HideIfSameAs": []},
    "HumanoidSwitchWeapon": {"Group": "OnFoot", "Category": "Combat", "Order": 124, "Name": "Switch WEP", "HideIfSameAs": []},
    "HumanoidThrowGrenadeButton": {"Group": "OnFoot", "Category": "Combat", "Order": 125, "Name": "Throw Grenade", "HideIfSameAs": []},
    "HumanoidToggleFlashlightButton": {"Group": "OnFoot", "Category": "Combat", "Order": 126, "Name": "Flashlight", "HideIfSameAs": []},
    "HumanoidToggleJumpAssistModuleButton": {"Group": "OnFoot", "Category": "Combat", "Order": 127, "Name": "Jump Assist", "HideIfSameAs": []},
    "HumanoidToggleMissionHelpPanelButton": {"Group": "OnFoot", "Category": "Combat", "Order": 128, "Name": "Mission Help", "HideIfSameAs": []},
    "HumanoidToggleNightVisionButton": {"Group": "OnFoot", "Category": "Combat", "Order": 129, "Name": "Night Vision", "HideIfSameAs": ["NightVisionToggle"]},
    "HumanoidToggleShieldBoosterModuleButton": {"Group": "OnFoot", "Category": "Combat", "Order": 130, "Name": "Shield Boost", "HideIfSameAs": []},
    "HumanoidToggleShieldsButton": {"Group": "OnFoot", "Category": "Combat", "Order": 131, "Name": "Shields", "HideIfSameAs": []},
    "HumanoidToggleToolModeButton": {"Group": "OnFoot", "Category": "Combat", "Order": 132, "Name": "Tool Mode", "HideIfSameAs": []},
    "HumanoidToggleWeaponBoosterModuleButton": {"Group": "OnFoot", "Category": "Combat", "Order": 134, "Name": "Weapon Booster", "HideIfSameAs": []},
    "HumanoidZoomButton": {"Group": "OnFoot", "Category": "Combat", "Order": 135, "Name": "ZoomButton", "HideIfSameAs": []},

    // Managing power
    "HumanoidResetPowerDistributionButton": {"Group": "OnFoot", "Category": "Combat", "Order": 201, "Name": "RST", "HideIfSameAs": ["ResetPowerDistribution"]},
    "HumanoidIncreaseEnginesPowerButton": {"Group": "OnFoot", "Category": "Combat", "Order": 202, "Name": "ENG", "HideIfSameAs": ["IncreaseEnginesPower"]},
    "HumanoidIncreaseSystemsPowerButton": {"Group": "OnFoot", "Category": "Combat", "Order": 203, "Name": "SYS", "HideIfSameAs": ["IncreaseSystemsPower"]},
    "HumanoidIncreaseWeaponsPowerButton": {"Group": "OnFoot", "Category": "Combat", "Order": 204, "Name": "WEP", "HideIfSameAs": ["IncreaseWeaponsPower"]},

    // Navigation
    "GalaxyMapOpen_Humanoid": {"Group": "OnFoot", "Category": "Navigation", "Order": 301, "Name": "GalMap", "HideIfSameAs": ["GalaxyMapOpen"]},
    "SystemMapOpen_Humanoid": {"Group": "OnFoot", "Category": "Navigation", "Order": 302, "Name": "SysMap", "HideIfSameAs": ["SystemMapOpen"]},

    // UI
    "FocusCommsPanel_Humanoid": {"Group": "OnFoot", "Order": 401, "Name": "Comms Panel", "HideIfSameAs": ["FocusCommsPanel"]},
    "QuickCommsPanel_Humanoid": {"Group": "OnFoot", "Order": 405, "Name": "Quick Comms", "HideIfSameAs": ["QuickCommsPanel"]},

    // Item Wheel
    "HumanoidItemWheelButton": {"Group": "OnFoot", "Order": 701, "Name": "Item Wheel", "HideIfSameAs": []},
    "HumanoidItemWheelButton_XAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 702, "Name": "Item L/R", "HideIfSameAs": []},
    "HumanoidItemWheelButton_XLeft": {"Group": "OnFoot", "Category": "Navigation", "Order": 703, "Name": "Item Left", "HideIfSameAs": []},
    "HumanoidItemWheelButton_XRight": {"Group": "OnFoot", "Category": "Navigation", "Order": 704, "Name": "Item Right", "HideIfSameAs": []},
    "HumanoidItemWheelButton_YAxis": {"Group": "OnFoot", "Category": "Navigation", "Order": 705, "Name": "Item Up/Dn", "HideIfSameAs": []},
    "HumanoidItemWheelButton_YDown": {"Group": "OnFoot", "Category": "Navigation", "Order": 706, "Name": "Item Down", "HideIfSameAs": []},
    "HumanoidItemWheelButton_YUp": {"Group": "OnFoot", "Category": "Navigation", "Order": 707, "Name": "Item Up", "HideIfSameAs": []},

    // Camera
    "PhotoCameraToggle_Humanoid": {"Group": "Camera", "Category": "Camera", "Order": 801, "Name": "External Cam", "HideIfSameAs": ["PhotoCameraToggle"]},
}

export const keymap = {
    "Comma": ",",
    "SemiColon": ";",
    "LeftAlt": "Left Alt",
    "LeftBracket": "[",
    "LeftControl": "Left Ctrl",
    "LeftShift": "Left Shift",
    "Minus": "-",
    "Plus": "+",
    "Equals": "=",
    "Period": ".",
    "RightAlt": "Right Alt",
    "RightBracket": "]",
    "RightControl": "Right Ctrl",
    "RightShift": "Right Shift",
    "RightArrow": "Right",
    "UpArrow": "Up",
    "LeftArrow": "Left",
    "DownArrow": "Down",
    "LessThan": "<",
    "GreaterThan": ">",
    "LeftParenthesis": "(",
    "RightParenthesis": ")",
    "Numpad_0": "Num 0",
    "Numpad_1": "Num 1",
    "Numpad_2": "Num 2",
    "Numpad_3": "Num 3",
    "Numpad_4": "Num 4",
    "Numpad_5": "Num 5",
    "Numpad_6": "Num 6",
    "Numpad_7": "Num 7",
    "Numpad_8": "Num 8",
    "Numpad_9": "Num 9",
    "Numpad_Decimal": "Num .",
    "Numpad_Multiply": "Num *",
    "Numpad_Divide": "Num /",
    "Numpad_Add": "Num +",
    "Numpad_Subtract": "Num -",
    "Numpad_Enter": "Num Enter",
    "Numpad_Equals": "Num =",
    "Numpad_Comma": "Num ,",
    "Numpad_Period": "Num .",
    "PageDown": "PgDn",
    "PageUp": "PgUp",
    "Grave": "`",
    "BackSlash": "\\",
    "Slash": "/",
    "Apostrophe": "\"",
    "Hash": "//",
}
